"""Brief 168: payment hold reaper.

Background loop that scans bookings with payment_expires_at set and:
1. Sends reminders when the deadline is approaching (configurable, default off)
2. Releases slots + marks status when the deadline has passed

Runs as a supervisord program alongside email_poller. Exits cleanly at startup
if the feature is disabled (no config), matching the email_poller pattern.

Reminders and expiry actions:
- For WhatsApp / Zernio DM customers (customer_phone looks like a conversation_id
  or real phone), send via the existing `send_whatsapp_message` helper which
  auto-detects Zernio vs Meta.
- For email customers (no customer_phone, customer_email set), skip actual send
  for now (log the event). A follow-up brief will add email reminder sending.

The reminder text is generated by marina_agent with a PAYMENT_REMINDER action
context so it stays in the agent's voice (CLAUDE.md Rule 3 compliance — no
static templates).
"""
import os
import sys
import time
from datetime import datetime, timezone

if __name__ == "__main__":
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from shared import state_registry, config_loader, bm_logger  # noqa: E402

POLL_INTERVAL_SECONDS = 60


def log(msg: str, **kwargs):
    bm_logger.log("hold_reaper", msg=msg, **kwargs)
    try:
        print(f"[hold_reaper] {msg} {kwargs}", flush=True)
    except Exception:
        pass


def _reminder_before_minutes() -> int:
    raw = config_loader.get_raw() or {}
    val = raw.get("booking_rules", {}).get("payment_reminder_before_minutes")
    try:
        return int(val) if val else 0
    except Exception:
        return 0


def _feature_enabled() -> bool:
    """Reaper runs if the client has payment hold_duration_hours configured
    AND payment.timing is upfront/deposit. Restaurant (timing=none) skips."""
    raw = config_loader.get_raw() or {}
    timing = raw.get("payment", {}).get("timing", "upfront")
    if timing not in ("upfront", "deposit"):
        return False
    hold_hours = raw.get("payment", {}).get("hold_duration_hours")
    return bool(hold_hours)


def _send_reminder(hold: dict):
    """Brief 168: send a Marina-generated reminder for a hold approaching expiry.
    For WhatsApp/Zernio customers only in this brief; email deferred to follow-up."""
    phone = hold.get("customer_phone") or ""
    if not phone:
        log("reminder_skip_no_phone", booking_ref=hold.get("booking_ref"))
        return
    try:
        from agents.marina import marina_agent
        # Minimal synthetic context — tell Marina there's a payment reminder to send.
        _fields = {
            "service_name": hold.get("service_key", ""),
            "date": hold.get("date", ""),
            "guests": str(hold.get("guests", "") or ""),
            "customer_name": hold.get("customer_name", "") or "",
        }
        _flags = {"_payment_reminder": True, "booking_ref": hold.get("booking_ref", "")}
        _ctx = (
            f"PAYMENT REMINDER: The customer placed a hold (ref {hold.get('booking_ref')}) "
            f"and received a payment link. The hold expires at {hold.get('payment_expires_at')}. "
            f"Write a SHORT, friendly reminder in the customer's most recent language. Do NOT "
            f"threaten to cancel. Do NOT mention exact expiry time. Tone: helpful check-in, "
            f"e.g. 'hey, just checking in on your booking — any issues with the payment link?'. "
            f"Include the booking ref. Keep it under 40 words."
        )
        result = marina_agent.process_message(
            from_email=phone, subject="", body="", thread_fields=_fields,
            thread_flags=_flags, action_context=_ctx, channel="whatsapp", messages=[],
        )
        reply_text = result.get("reply", "").strip()
        if not reply_text:
            log("reminder_skip_empty_reply", booking_ref=hold.get("booking_ref"))
            return
        from agents.social.whatsapp_client import send_whatsapp_message
        ok = send_whatsapp_message(phone, reply_text)
        if ok:
            state_registry.mark_payment_reminder_sent(hold["id"])
            log("reminder_sent", booking_ref=hold.get("booking_ref"), phone=phone[:12])
        else:
            log("reminder_send_failed", booking_ref=hold.get("booking_ref"))
    except Exception as e:
        log("reminder_error", booking_ref=hold.get("booking_ref"), error=str(e))


def _expire_hold(hold: dict):
    """Brief 168: mark a hold as payment_expired, release the slot via cancel_hold,
    and log the action. Does NOT notify the customer in this brief — a follow-up
    brief will add "your slot was released" messages."""
    try:
        state_registry.cancel_hold(hold["id"])
        state_registry.expire_payment_hold(hold["id"])
        log("hold_expired_released",
            booking_ref=hold.get("booking_ref"),
            service_key=hold.get("service_key"),
            date=hold.get("date"),
            slot_time=hold.get("slot_time"))
    except Exception as e:
        log("expire_error", booking_ref=hold.get("booking_ref"), error=str(e))


def _tick():
    """One poll iteration: scan for reminders + expirations."""
    now_iso = datetime.now(timezone.utc).isoformat()
    reminder_before = _reminder_before_minutes()
    if reminder_before > 0:
        due_reminders = state_registry.get_holds_needing_reminder(now_iso, reminder_before)
        for hold in due_reminders:
            _send_reminder(hold)
    expired = state_registry.get_expired_payment_holds(now_iso)
    for hold in expired:
        _expire_hold(hold)


def main():
    if not _feature_enabled():
        log("startup_skip_feature_disabled",
            reason="payment.timing != upfront/deposit OR no hold_duration_hours")
        return
    log("startup", poll_interval_seconds=POLL_INTERVAL_SECONDS,
        reminder_before_minutes=_reminder_before_minutes())
    while True:
        try:
            _tick()
        except Exception as e:
            log("tick_error", error=str(e))
        time.sleep(POLL_INTERVAL_SECONDS)


if __name__ == "__main__":
    main()
